version: "2"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MSQL_USER: chat-user
      MSQL_PASSWORD: password
    ports:
    - "3307:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/chat-api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
     DB_USERNAME: chat-user
     DB_PASSWORD: password
     DB_DATABASE: chat-api
     DB_PORT: "3306"
     DB_HOST: db
     RAILS_MAX_THREADS: 5
     